#  Revenue & Customer Intelligence Platform

## Import the all Required LIbraries.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sc

## Load all the Dataset

In [2]:
# Full absolute path to your folder
folder_path = "/home/ashutosh/Desktop/Revenue & Customer Intelligence Platform/olistdataser"

orders = pd.read_csv(f"{folder_path}/olist_orders_dataset.csv")
customers = pd.read_csv(f"{folder_path}/olist_customers_dataset.csv")
order_items = pd.read_csv(f"{folder_path}/olist_order_items_dataset.csv")
products = pd.read_csv(f"{folder_path}/olist_products_dataset.csv")
payments = pd.read_csv(f"{folder_path}/olist_order_payments_dataset.csv")
sellers = pd.read_csv(f"{folder_path}/olist_sellers_dataset.csv")
geolocation = pd.read_csv(f"{folder_path}/olist_geolocation_dataset.csv")
reviews = pd.read_csv(f"{folder_path}/olist_order_reviews_dataset.csv")
category_translation = pd.read_csv(f"{folder_path}/product_category_name_translation.csv")

## Step - 2 : Data Profiling & Data Quality Assessment

### 1️⃣ ORDERS TABLE AUDIT

In [3]:
print("ORDERS INFO")
orders.info()

ORDERS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [4]:
print("\nORDERS HEAD")
print(orders.head(5))

ORDERS HEAD
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

In [5]:
print("\nORDERS DESCRIBE")
print(orders.describe(include='all'))

ORDERS DESCRIBE
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-08-02 12:06:07  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-14 20:02:44
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522

### 2️⃣ CUSTOMERS TABLE AUDIT

In [6]:
print("CUSTOMERS INFO")
customers.info()

CUSTOMERS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [7]:
print("\nCUSTOMERS HEAD")
print(customers.head())

CUSTOMERS HEAD
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

In [8]:
print("\nCUSTOMERS DESCRIBE")
print(customers.describe(include='all'))

CUSTOMERS DESCRIBE
                             customer_id                customer_unique_id  \
count                              99441                             99441
unique                             99441                             96096
top     274fa6071e5e17fe303b9748641082c8  8d50f5eadf50201ccdcedfb9e2ac8455
freq                                   1                                17
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        customer_zip_code_prefix customer_city customer_state
count               99441.000000         99441          99441
unique                       NaN          4119             27
top                          NaN     sao paulo             SP
freq                         NaN         15540          41746
mean                35137.474583           NaN            NaN
std                 29797.938996           NaN            NaN
min                  1003.000000           NaN            NaN
25%                 11347.000000           NaN            NaN
50%                 24416.000000           NaN            NaN
75%                 58900.000000           NaN            NaN
max                 99990.000000           NaN            NaN

### 🔎 3️⃣ ORDER ITEMS TABLE AUDIT

In [9]:
print("ORDER ITEMS INFO")
order_items.info()

ORDER ITEMS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [10]:
print("\nORDER ITEMS HEAD")
print(order_items.head())

ORDER ITEMS HEAD
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14

In [11]:
print("\nORDER ITEMS DESCRIBE")
print(order_items.describe(include='all'))

ORDER ITEMS DESCRIBE
                                order_id  order_item_id  \
count                             112650  112650.000000
unique                             98666            NaN
top     8272b63d03f5f79c56e9e4120aec44ef            NaN
freq                                  21            NaN
mean                                 NaN       1.197834
std                                  NaN       0.705124
min                                  NaN       1.000000
25%                                  NaN       1.000000
50%                                  NaN       1.000000
75%                                  NaN       1.000000
max                                  NaN      21.000000

                              product_id                         seller_id  \
count                             112650                            112650
unique                             32951                              3095
top     aca2eb7d00ea1a7b8ebd4e68314663af  6560211a19b47992c3666cc44a7e94c0
freq                                 527                              2033
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        shipping_limit_date          price  freight_value
count                112650  112650.000000  112650.000000
unique                93318            NaN            NaN
top     2017-07-21 18:25:23            NaN            NaN
freq                     21            NaN            NaN
mean                    NaN     120.653739      19.990320
std                     NaN     183.633928      15.806405
min                     NaN       0.850000       0.000000
25%                     NaN      39.900000      13.080000
50%                     NaN      74.990000      16.260000
75%                     NaN     134.900000      21.150000
max                     NaN    6735.000000     409.680000

### 4️⃣ PRODUCTS TABLE AUDIT

In [12]:
print("PRODUCTS INFO")
products.info()

PRODUCTS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [13]:
print("\nPRODUCTS HEAD")
print(products.head())

PRODUCTS HEAD
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

In [14]:
print("\nPRODUCTS DESCRIBE")
print(products.describe(include='all'))

PRODUCTS DESCRIBE
                              product_id product_category_name  \
count                              32951                 32341
unique                             32951                    73
top     106392145fca363410d287a815be6de4       cama_mesa_banho
freq                                   1                  3029
mean                                 NaN                   NaN
std                                  NaN                   NaN
min                                  NaN                   NaN
25%                                  NaN                   NaN
50%                                  NaN                   NaN
75%                                  NaN                   NaN
max                                  NaN                   NaN

        product_name_lenght  product_description_lenght  product_photos_qty  \
count          32341.000000                32341.000000        32341.000000
unique                  NaN                         NaN                 NaN
top                     NaN                         NaN                 NaN
freq                    NaN                         NaN                 NaN
mean              48.476949                  771.495285            2.188986
std               10.245741                  635.115225            1.736766
min                5.000000                    4.000000            1.000000
25%               42.000000                  339.000000            1.000000
50%               51.000000                  595.000000            1.000000
75%               57.000000                  972.000000            3.000000
max               76.000000                 3992.000000           20.000000

        product_weight_g  product_length_cm  product_height_cm  \
count       32949.000000       32949.000000       32949.000000
unique               NaN                NaN                NaN
top                  NaN                NaN                NaN
freq                 NaN                NaN                NaN
mean         2276.472488          30.815078          16.937661
std          4282.038731          16.914458          13.637554
min             0.000000           7.000000           2.000000
25%           300.000000          18.000000           8.000000
50%           700.000000          25.000000          13.000000
75%          1900.000000          38.000000          21.000000
max         40425.000000         105.000000         105.000000

        product_width_cm
count       32949.000000
unique               NaN
top                  NaN
freq                 NaN
mean           23.196728
std            12.079047
min             6.000000
25%            15.000000
50%            20.000000
75%            30.000000
max           118.000000

### 🔎 5️⃣ PAYMENTS TABLE AUDIT

In [15]:
print("PAYMENTS INFO")
payments.info()

PAYMENTS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [16]:
print("\nPAYMENTS HEAD")
print(payments.head())

PAYMENTS HEAD
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

In [17]:
print("\nPAYMENTS DESCRIBE")
print(payments.describe(include='all'))

PAYMENTS DESCRIBE
                                order_id  payment_sequential payment_type  \
count                             103886       103886.000000       103886
unique                             99440                 NaN            5
top     fa65dad1b0e818e3ccc5cb0e39231352                 NaN  credit_card
freq                                  29                 NaN        76795
mean                                 NaN            1.092679          NaN
std                                  NaN            0.706584          NaN
min                                  NaN            1.000000          NaN
25%                                  NaN            1.000000          NaN
50%                                  NaN            1.000000          NaN
75%                                  NaN            1.000000          NaN
max                                  NaN           29.000000          NaN

        payment_installments  payment_value
count          103886.000000  103886.000000
unique                   NaN            NaN
top                      NaN            NaN
freq                     NaN            NaN
mean                2.853349     154.100380
std                 2.687051     217.494064
min                 0.000000       0.000000
25%                 1.000000      56.790000
50%                 1.000000     100.000000
75%                 4.000000     171.837500
max                24.000000   13664.080000

 ### 6️⃣ SELLERS TABLE AUDIT

In [18]:
print("SELLERS INFO")
sellers.info()

SELLERS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [19]:
print("\nSELLERS HEAD")
print(sellers.head())

SELLERS HEAD
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

In [20]:
print("\nSELLERS DESCRIBE")
print(sellers.describe(include='all'))

SELLERS DESCRIBE
                               seller_id  seller_zip_code_prefix seller_city  \
count                               3095             3095.000000        3095
unique                              3095                     NaN         611
top     9e25199f6ef7e7c347120ff175652c3b                     NaN   sao paulo
freq                                   1                     NaN         694
mean                                 NaN            32291.059451         NaN
std                                  NaN            32713.453830         NaN
min                                  NaN             1001.000000         NaN
25%                                  NaN             7093.500000         NaN
50%                                  NaN            14940.000000         NaN
75%                                  NaN            64552.500000         NaN
max                                  NaN            99730.000000         NaN

       seller_state
count          3095
unique           23
top              SP
freq           1849
mean            NaN
std             NaN
min             NaN
25%             NaN
50%             NaN
75%             NaN
max             NaN

### 7️⃣ GEOLOCATION TABLE AUDIT

In [21]:
print("GEOLOCATION INFO")
geolocation.info()

GEOLOCATION INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [22]:
print("\nGEOLOCATION HEAD")
print(geolocation.head())

GEOLOCATION HEAD
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP

In [23]:
print("\nGEOLOCATION DESCRIBE")
print(geolocation.describe(include='all'))

GEOLOCATION DESCRIBE
        geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
count                  1.000163e+06     1.000163e+06     1.000163e+06
unique                          NaN              NaN              NaN
top                             NaN              NaN              NaN
freq                            NaN              NaN              NaN
mean                   3.657417e+04    -2.117615e+01    -4.639054e+01
std                    3.054934e+04     5.715866e+00     4.269748e+00
min                    1.001000e+03    -3.660537e+01    -1.014668e+02
25%                    1.107500e+04    -2.360355e+01    -4.857317e+01
50%                    2.653000e+04    -2.291938e+01    -4.663788e+01
75%                    6.350400e+04    -1.997962e+01    -4.376771e+01
max                    9.999000e+04     4.506593e+01     1.211054e+02

       geolocation_city geolocation_state
count           1000163           1000163
unique             8011                27
top           sao paulo                SP
freq             135800            404268
mean                NaN               NaN
std                 NaN               NaN
min                 NaN               NaN
25%                 NaN               NaN
50%                 NaN               NaN
75%                 NaN               NaN
max                 NaN               NaN

### 🔎 8️⃣ REVIEWS TABLE AUDIT

In [24]:
print("REVIEWS INFO")
reviews.info()

REVIEWS INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [25]:
print("\nREVIEWS HEAD")
print(reviews.head())

REVIEWS HEAD
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

In [26]:
print("\nREVIEWS DESCRIBE")
print(reviews.describe(include='all'))

REVIEWS DESCRIBE
                               review_id                          order_id  \
count                              99224                             99224
unique                             98410                             98673
top     4548534449b1f572e357211b90724f1b  03c939fd7fd3b38f8485a0f95798f1f6
freq                                   3                                 3
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        review_score review_comment_title review_comment_message  \
count   99224.000000                11568                  40977
unique           NaN                 4527                  36159
top              NaN            Recomendo              Muito bom
freq             NaN                  423                    230
mean        4.086421                  NaN                    NaN
std         1.347579                  NaN                    NaN
min         1.000000                  NaN                    NaN
25%         4.000000                  NaN                    NaN
50%         5.000000                  NaN                    NaN
75%         5.000000                  NaN                    NaN
max         5.000000                  NaN                    NaN

       review_creation_date review_answer_timestamp
count                 99224                   99224
unique                  636                   98248
top     2017-12-19 00:00:00     2017-06-15 23:21:05
freq                    463                       4
mean                    NaN                     NaN
std                     NaN                     NaN
min                     NaN                     NaN
25%                     NaN                     NaN
50%                     NaN                     NaN
75%                     NaN                     NaN
max                     NaN                     NaN

###  9️⃣ CATEGORY TRANSLATION TABLE AUDIT

In [27]:
print("CATEGORY TRANSLATION INFO")
category_translation.info()

CATEGORY TRANSLATION INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [28]:
print("\nCATEGORY TRANSLATION HEAD")
print(category_translation.head())

CATEGORY TRANSLATION HEAD
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [29]:
print("\nCATEGORY TRANSLATION DESCRIBE")
print(category_translation.describe(include='all'))

CATEGORY TRANSLATION DESCRIBE
       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

### NDUSTRY DATA SUMMARY TABLE

In [30]:
tables = {
    "orders": orders,
    "customers": customers,
    "order_items": order_items,
    "products": products,
    "payments": payments,
    "sellers": sellers,
    "geolocation": geolocation,
    "reviews": reviews,
    "category_translation": category_translation
}

summary = []

for name, df in tables.items():
    summary.append([
        name,
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum()
    ])

summary_df = pd.DataFrame(summary, columns=["Table", "Rows", "Columns", "Total Missing Values"])
summary_df

                  Table     Rows  Columns  Total Missing Values
0                orders    99441        8                  4908
1             customers    99441        5                     0
2           order_items   112650        7                     0
3              products    32951        9                  2448
4              payments   103886        5                     0
5               sellers     3095        4                     0
6           geolocation  1000163        5                     0
7               reviews    99224        7                145903
8  category_translation       71        2                     0

## Step - 3 : Cleaning + Transforming + Preparing analysis dataset

### Filter Valid Orders

In [31]:
orders = orders[orders['order_status'] == 'delivered']

In [32]:
orders.shape

(96478, 8)

### Convert Date Columns to Datetime

In [33]:
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

/tmp/ipykernel_14453/3193841261.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[col] = pd.to_datetime(orders[col])
/tmp/ipykernel_14453/3193841261.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[col] = pd.to_datetime(orders[col])
/tmp/ipykernel_14453/3193841261.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[col] = pd.to_datetime(orders[col])
/tmp/ipykernel_14453/3193841261.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[col] = pd.to_datetime(orders[col])
/tmp/ipykernel_14453/3193841261.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders[col] = pd.to_datetime(orders[col])

In [34]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96478 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96478 non-null  object
 1   customer_id                    96478 non-null  object
 2   order_status                   96478 non-null  object
 3   order_purchase_timestamp       96478 non-null  datetime64[ns]
 4   order_approved_at              96464 non-null  datetime64[ns]
 5   order_delivered_carrier_date   96476 non-null  datetime64[ns]
 6   order_delivered_customer_date  96470 non-null  datetime64[ns]
 7   order_estimated_delivery_date  96478 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.6+ MB

### Handle Missing ValuesA

In [35]:
orders.isnull().sum()

order_id                          0
customer_id                       0
order_status                      0
order_purchase_timestamp          0
order_approved_at                14
order_delivered_carrier_date      2
order_delivered_customer_date     8
order_estimated_delivery_date     0
dtype: int64

In [36]:
orders = orders.dropna(subset=['order_delivered_customer_date'])

In [37]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [38]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [39]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [40]:
products['product_category_name'] = products['product_category_name'].fillna('Unknown')
products['product_weight_g'] = products['product_weight_g'].fillna(products['product_weight_g'].median())

In [41]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [42]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [43]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [44]:
geo_clean = geolocation.groupby('geolocation_zip_code_prefix').agg({
    'geolocation_lat': 'mean',
    'geolocation_lng': 'mean'
}).reset_index()

In [45]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [46]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [47]:
dfs = {
    'orders': orders,
    'customers': customers,
    'order_items': order_items,
    'products': products,
    'payments': payments,
    'sellers': sellers,
    'geolocation': geolocation,
    'reviews': reviews,
    'category_translation': category_translation
}

for name, df in dfs.items():
    null_count = df.isnull().sum().sum() # Poori table ke total null values
    print(f"Table: {name} | Total Nulls: {null_count}")

Table: orders | Total Nulls: 15
Table: customers | Total Nulls: 0
Table: order_items | Total Nulls: 0
Table: products | Total Nulls: 1836
Table: payments | Total Nulls: 0
Table: sellers | Total Nulls: 0
Table: geolocation | Total Nulls: 0
Table: reviews | Total Nulls: 145903
Table: category_translation | Total Nulls: 0

In [48]:
df.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

### Handling Duplicate

In [49]:
dfs = {
    'orders': orders,
    'customers': customers,
    'order_items': order_items,
    'products': products,
    'payments': payments,
    'sellers': sellers,
    'geolocation': geolocation,
    'reviews': reviews,
    'category_translation': category_translation
}

for name, df in dfs.items():
    null_count = df.duplicated().sum().sum() 
    print(f"Table: {name} | Total Duplicates: {null_count}")

Table: orders | Total Duplicates: 0
Table: customers | Total Duplicates: 0
Table: order_items | Total Duplicates: 0
Table: products | Total Duplicates: 0
Table: payments | Total Duplicates: 0
Table: sellers | Total Duplicates: 0
Table: geolocation | Total Duplicates: 261831
Table: reviews | Total Duplicates: 0
Table: category_translation | Total Duplicates: 0

### Merge All Tables (Create Master Dataset) : ETL (Extract, Transform, Load) Process

In [50]:
df = orders.merge(order_items, on='order_id', how='inner')

In [51]:
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110184,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10
110185,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02
110186,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
110187,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
110188,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [52]:
df = df.merge(products, on='product_id', how='left')

In [53]:
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1,d0b61bfb1de832b15ba9d266ca96e5b0,...,45.00,27.20,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1,65266b2da20d04dbe00c5c2d3bb7859e,...,19.90,8.72,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110184,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,174.90,20.10,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
110185,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,1,b80910977a37536adeddd63663f916ad,...,205.99,65.02,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
110186,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,1,d1c427060a0f73f6b889a5c7c61f2ac4,...,179.99,40.59,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
110187,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,2,d1c427060a0f73f6b889a5c7c61f2ac4,...,179.99,40.59,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
110188,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,1,006619bbed68b000c8ba3f8725d5409e,...,68.50,18.36,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0

In [54]:
df = df.merge(customers, on='customer_id', how='left')

In [55]:
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,178.0,1.0,400.0,19.0,13.0,19.0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,232.0,1.0,420.0,24.0,19.0,21.0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,1,d0b61bfb1de832b15ba9d266ca96e5b0,...,468.0,3.0,450.0,30.0,10.0,20.0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,1,65266b2da20d04dbe00c5c2d3bb7859e,...,316.0,4.0,250.0,51.0,15.0,15.0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110184,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,828.0,4.0,4950.0,40.0,10.0,40.0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP
110185,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,1,b80910977a37536adeddd63663f916ad,...,500.0,2.0,13300.0,32.0,90.0,22.0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA
110186,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,1,d1c427060a0f73f6b889a5c7c61f2ac4,...,1893.0,1.0,6550.0,20.0,20.0,20.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ
110187,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,2,d1c427060a0f73f6b889a5c7c61f2ac4,...,1893.0,1.0,6550.0,20.0,20.0,20.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ
110188,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,1,006619bbed68b000c8ba3f8725d5409e,...,569.0,1.0,150.0,16.0,7.0,15.0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR

In [56]:
df = df.merge(payments, on='order_id', how='left')

In [57]:
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,13.0,19.0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,19.0,21.0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,credit_card,3.0,179.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115025,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,10.0,40.0,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,1.0,credit_card,3.0,195.00
115026,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,1,b80910977a37536adeddd63663f916ad,...,90.0,22.0,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA,1.0,credit_card,5.0,271.01
115027,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,1,d1c427060a0f73f6b889a5c7c61f2ac4,...,20.0,20.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,1.0,credit_card,4.0,441.16
115028,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,2,d1c427060a0f73f6b889a5c7c61f2ac4,...,20.0,20.0,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,1.0,credit_card,4.0,441.16
115029,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,1,006619bbed68b000c8ba3f8725d5409e,...,7.0,15.0,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,1.0,debit_card,1.0,86.86

In [58]:
df = df.merge(sellers, on='seller_id', how='left')

In [59]:
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,customer_zip_code_prefix,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,3149,sao paulo,SP,1.0,credit_card,1.0,18.12,9350,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,3149,sao paulo,SP,3.0,voucher,1.0,2.00,9350,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,3149,sao paulo,SP,2.0,voucher,1.0,18.59,9350,maua,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,47813,barreiras,BA,1.0,boleto,1.0,141.46,31570,belo horizonte,SP
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,75265,vianopolis,GO,1.0,credit_card,3.0,179.12,14840,guariba,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115025,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,11722,praia grande,SP,1.0,credit_card,3.0,195.00,17602,tupa,SP
115026,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,1,b80910977a37536adeddd63663f916ad,...,45920,nova vicosa,BA,1.0,credit_card,5.0,271.01,8290,sao paulo,SP
115027,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,1,d1c427060a0f73f6b889a5c7c61f2ac4,...,28685,japuiba,RJ,1.0,credit_card,4.0,441.16,37175,ilicinea,MG
115028,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,2,d1c427060a0f73f6b889a5c7c61f2ac4,...,28685,japuiba,RJ,1.0,credit_card,4.0,441.16,37175,ilicinea,MG
115029,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,1,006619bbed68b000c8ba3f8725d5409e,...,83750,lapa,PR,1.0,debit_card,1.0,86.86,14407,franca,SP

In [216]:
df.to_csv("df.csv", index=False)
print("CSV saved successfully!")

CSV saved successfully!

### Create Revenue Column

In [60]:
df['revenue'] = df['price'] + df['freight_value']

### Create Profit (Assumption Model)

In [61]:
df['cost'] = df['price'] * 0.8
df['profit'] = df['revenue'] - df['cost']

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115030 entries, 0 to 115029
Data columns (total 33 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115030 non-null  object
 1   customer_id                    115030 non-null  object
 2   order_status                   115030 non-null  object
 3   order_purchase_timestamp       115030 non-null  datetime64[ns]
 4   order_approved_at              115015 non-null  datetime64[ns]
 5   order_delivered_carrier_date   115029 non-null  datetime64[ns]
 6   order_delivered_customer_date  115030 non-null  datetime64[ns]
 7   order_estimated_delivery_date  115030 non-null  datetime64[ns]
 8   order_item_id                  115030 non-null  int64
 9   product_id                     115030 non-null  object
 10  seller_id                      115030 non-null  object
 11  shipping_limit_date            115030 non-null  object
 12  price                          115030 non-null  float64
 13  freight_value                  115030 non-null  float64
 14  product_category_name          115030 non-null  object
 15  product_name_lenght            113402 non-null  float64
 16  product_description_lenght     113402 non-null  float64
 17  product_photos_qty             113402 non-null  float64
 18  product_weight_g               115030 non-null  float64
 19  product_length_cm              115030 non-null  float64
 20  product_height_cm              115030 non-null  float64
 21  product_width_cm               115030 non-null  float64
 22  customer_unique_id             115030 non-null  object
 23  customer_zip_code_prefix       115030 non-null  int64
 24  customer_city                  115030 non-null  object
 25  customer_state                 115030 non-null  object
 26  payment_sequential             115027 non-null  float64
 27  payment_type                   115027 non-null  object
 28  payment_installments           115027 non-null  float64
 29  payment_value                  115027 non-null  float64
 30  seller_zip_code_prefix         115030 non-null  int64
 31  seller_city                    115030 non-null  object
 32  seller_state                   115030 non-null  object
dtypes: datetime64[ns](5), float64(12), int64(3), object(13)
memory usage: 29.0+ MB

### Create Time Features

In [62]:
df['year'] = df['order_purchase_timestamp'].dt.year
df['month'] = df['order_purchase_timestamp'].dt.month
df['day'] = df['order_purchase_timestamp'].dt.day
df['weekday'] = df['order_purchase_timestamp'].dt.day_name()

###  Validate Final Dataset

In [63]:
df.shape

(115030, 40)

In [64]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,seller_zip_code_prefix,seller_city,seller_state,revenue,cost,profit,year,month,day,weekday
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,9350,maua,SP,38.71,23.992,14.718,2017,10,2,Monday
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,9350,maua,SP,38.71,23.992,14.718,2017,10,2,Monday
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,9350,maua,SP,38.71,23.992,14.718,2017,10,2,Monday
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,31570,belo horizonte,SP,141.46,94.960,46.500,2018,7,24,Tuesday
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,14840,guariba,SP,179.12,127.920,51.200,2018,8,8,Wednesday

In [64]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date        1
order_delivered_customer_date       0
order_estimated_delivery_date       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
product_category_name               0
product_name_lenght              1628
product_description_lenght       1628
product_photos_qty               1628
product_weight_g                    0
product_length_cm                   0
product_height_cm                   0
product_width_cm                    0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
dtype: int64

In [66]:
df.shape

(115030, 40)

In [67]:
df = df.dropna(subset=[
    'order_approved_at',
    'order_delivered_carrier_date'
])

In [63]:
for col in ['product_length_cm', 'product_height_cm', 'product_width_cm']:
    df[col] = df[col].fillna(df[col].median())

In [70]:
df[df['payment_value'].isnull()]
df = df[df['payment_value'].notnull()]

In [71]:
print("Negative revenue:", (df['revenue'] < 0).sum())
print("Negative profit:", (df['profit'] < 0).sum())

Negative revenue: 0
Negative profit: 0

In [72]:
df1 = df.copy()

## Step - 4 : Executive KPI Overview

### 1. Executive KPI(Key,Performance,Indicator) Overview –
- First high-level section of the dashboard/report
- Made specially for CEOs, founders, executives
- Shows only the most critical 5–8 numbers
- Goal: Understand business health in 10–30 seconds
- Also called: Executive Summary / KPI Snapshot / At-a-Glance Dashboard

### 2. Main KPIs usually included (your project)
- Total Revenue
- Total Profit
- Profit Margin %
- Total Orders
- Total Unique Customers
- Average Order Value (AOV)
- (Optional extras): Monthly Growth %, Top Category Share, New vs Returning Customers

### 3. Why this section is always first & very important
- Executives are very busy → no time for long reports
- Gives instant big picture (growth? profit? problems?)
- Early warning system (margin dropping = danger)
- Same numbers for all leaders → no arguments
- Looks professional for investors / board meetings
- Saves hours of explanation in meetings

### 4. Typical look on dashboard
Big bold cards / tiles:
- 💰 Revenue: ₹1.61 Cr
- 📈 Profit: ₹50.6 Lakh (31.4%)
- 🛒 Orders: XXXX
- 👥 Customers: 93,335
- 🛍️ AOV: ₹XXX

Green = good | Red/Yellow = attention needed

### 5. What comes after Executive KPI Overview (your project flow)
1. Executive KPI Overview → big numbers
2. Monthly Revenue Trend → line chart (growth + seasonality)
3. Category Performance → top categories (bar chart)
4. Geographic / State Analysis → map or bars by state
5. RFM Customer Segments → pie + revenue by segment
6. Pareto (80/20) → cumulative revenue curve
7. (Bonus) Profitability Deep Dive → negative orders, freight ratio, low margin areas

### 6. Quick business value of having this section
- Faster decisions (raise price? cut cost? promote?)
- Immediate red-flag detection
- Professional presentation (investors love it)
- Starting point before deep analysis
- Shows you understand what really matters to business

### 7. One-line definition
**Executive KPI Overview = The 10-second heartbeat of the entire business.**

In [122]:
df.info()

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
<class 'pandas.core.frame.DataFrame'>
Index: 115011 entries, 0 to 115029
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115011 non-null  object
 1   customer_id                    115011 non-null  object
 2   order_status                   115011 non-null  object
 3   order_purchase_timestamp       115011 non-null  datetime64[ns]
 4   order_approved_at              115011 non-null  datetime64[ns]
 5   order_delivered_carrier_date   115011 non-null  datetime64[ns]
 6   order_delivered_customer_date  115011 non-null  datetime64[ns]
 7   order_estimated_delivery_date  115011 non-null  datetime64[ns]
 8   order_item_id                  115011 non-null  int64
 9   product_id                     115011 non-null  object
 10  seller_id                      115011 non-null  object
 11  shipping_limit_date            115011 non-null  object
 12  price                          115011 non-null  float64
 13  freight_value                  115011 non-null  float64
 14  product_category_name          115011 non-null  object
 15  product_name_lenght            113384 non-null  float64
 16  product_description_lenght     113384 non-null  float64
 17  product_photos_qty             113384 non-null  float64
 18  product_weight_g               115011 non-null  float64
 19  product_length_cm              115011 non-null  float64
 20  product_height_cm              115011 non-null  float64
 21  product_width_cm               115011 non-null  float64
 22  customer_unique_id             115011 non-null  object
 23  customer_zip_code_prefix       115011 non-null  int64
 24  customer_city                  115011 non-null  object
 25  customer_state                 115011 non-null  object
 26  payment_sequential             115011 non-null  float64
 27  payment_type                   115011 non-null  object
 28  payment_installments           115011 non-null  float64
 29  payment_value                  115011 non-null  float64
 30  seller_zip_code_prefix         115011 non-null  int64
 31  seller_city                    115011 non-null  object
 32  seller_state                   115011 non-null  object
 33  revenue                        115011 non-null  float64
 34  cost                           115011 non-null  float64
 35  profit                         115011 non-null  float64
 36  year                           115011 non-null  int32
 37  month                          115011 non-null  int32
 38  day                            115011 non-null  int32
 39  weekday                        115011 non-null  object
 40  purchase_month                 115011 non-null  period[M]
 41  cohort_month                   115011 non-null  period[M]
 42  cohort_index                   115011 non-null  int64
 43  freight_ratio                  115011 non-null  float64
dtypes: datetime64[ns](5), float64(16), int32(3), int64(4), object(14), period[M](2)
memory usage: 38.2+ MB

### Metrics to Calculate:

In [73]:
total_revenue = df['revenue'].sum()
total_profit = df['profit'].sum()
total_orders = df['order_id'].nunique()
total_customers = df['customer_unique_id'].nunique()
avg_order_value = df['revenue'].mean()

In [74]:
profit_margin = (total_profit / total_revenue) * 100

### Monthly Revenue & Growth Trend

In [75]:
monthly_revenue = df.groupby(['year','month'])['revenue'].sum().reset_index()

In [76]:
monthly_revenue['growth_%'] = monthly_revenue['revenue'].pct_change() * 100

### Category Performance Analysis

In [77]:
category_performance = df.groupby('product_category_name').agg({
    'revenue':'sum',
    'profit':'sum',
    'order_id':'count'
}).reset_index()

In [78]:
category_performance.sort_values('revenue', ascending=False)

            product_category_name     revenue      profit  order_id
12                   beleza_saude  1456026.83  438960.198      9759
67             relogios_presentes  1315013.93  344483.690      6063
14                cama_mesa_banho  1292422.04  430154.728     11649
33                  esporte_lazer  1159638.36  367321.368      8730
45         informatica_acessorios  1068666.04  333595.744      7897
..                            ...         ...         ...       ...
61                       pc_gamer     1575.17     425.618         9
16                casa_conforto_2     1194.44     575.904        31
18              cds_dvds_musicais      954.99     370.990        14
38  fashion_roupa_infanto_juvenil      598.67     182.710         7
68             seguros_e_servicos      324.51      97.878         2

[74 rows x 4 columns]

### RFM Customer Segmentation

R (Recency) → Days since last purchase

F (Frequency) → Total orders per customer

M (Monetary) → Total revenue per customer

In [79]:
# Make sure timestamp is datetime
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

# Reference date (max date in dataset)
reference_date = df['order_purchase_timestamp'].max()

In [80]:
rfm = df.groupby('customer_unique_id').agg({
    'order_purchase_timestamp': lambda x: (reference_date - x.max()).days,  # Recency
    'order_id': 'nunique',  # Frequency
    'revenue': 'sum'  # Monetary
}).reset_index()

rfm.columns = ['customer_unique_id', 'Recency', 'Frequency', 'Monetary']

In [81]:
rfm.head()

                 customer_unique_id  Recency  Frequency  Monetary
0  0000366f3b9a7992bf8c76cfdf3221e2      111          1    141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f      114          1     27.19
2  0000f46a3911fa3c0805444483337064      536          1     86.22
3  0000f6ccb0745a6a4b88665a16c9f078      320          1     43.62
4  0004aac84e0df4da2b147fca70cf8255      287          1    196.89


### Recency Scoring 
Lower recency = better customer ;
So reverse scoring.

In [82]:
rfm['R_score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4,3,2,1])

In [83]:
rfm['R_score']

0        4
1        4
2        1
3        2
4        2
        ..
93330    1
93331    3
93332    1
93333    4
93334    1
Name: R_score, Length: 93335, dtype: category
Categories (5, int64): [5 < 4 < 3 < 2 < 1]

### Frequency Scoring
Higher frequency = better

In [84]:
rfm['F_score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])

### Monetary Scoring
Higher spending = better

In [85]:
rfm['M_score'] = pd.qcut(rfm['Monetary'], 5, labels=[1,2,3,4,5])

### Create RFM Score

In [86]:
rfm['RFM_Score'] = (
    rfm['R_score'].astype(str) +
    rfm['F_score'].astype(str) +
    rfm['M_score'].astype(str)
)

In [87]:
rfm['RFM_Score'].head()

0    414
1    411
2    112
3    211
4    214
Name: RFM_Score, dtype: object

In [88]:
def segment_customer(row):
    if row['R_score'] == 5 and row['F_score'] == 5 and row['M_score'] == 5:
        return 'Champions'
    elif row['R_score'] >= 4 and row['F_score'] >= 4:
        return 'Loyal Customers'
    elif row['R_score'] <= 2:
        return 'At Risk'
    else:
        return 'Regular'

rfm['Segment'] = rfm.apply(segment_customer, axis=1)

In [155]:
rfm['Segment'].head()
rfm['Segment'].value_counts()

Segment
Regular            41177
At Risk            37199
Loyal Customers    13976
Champions            983
Name: count, dtype: int64

### CLV (Customer Lifetime Value)

In [90]:
customer_clv = df.groupby('customer_unique_id')['revenue'].sum().reset_index()

### State-wise / Regional Analysis

In [91]:
state_performance = df.groupby('customer_state').agg({
    'revenue':'sum',
    'profit':'sum',
    'order_id':'count'
}).reset_index()

In [124]:
state_performance.head()

  customer_state    revenue      profit  order_id
0             AC   20767.13    7161.162        94
1             AL   97422.10   32101.084       441
2             AM   28215.64   10128.952       169
3             AP   16396.40    5552.552        83
4             BA  624810.85  208056.954      3930

### Profitability Deep Dive

In [125]:
negative_profit_orders = df[df['profit'] < 0]

In [128]:
negative_profit_orders

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state, payment_sequential, payment_type, payment_installments, payment_value, seller_zip_code_prefix, seller_city, seller_state, revenue, cost, profit, year, month, day, weekday, purchase_month, cohort_month, cohort_index, freight_ratio]
Index: []

[0 rows x 44 columns]

## STEP 5 – CUSTOMER & PROFIT INTELLIGENCE FRAMEWORK

### 1. Revenue Contribution by Customer Segment
- Merges RFM segments to orders
- Calculates revenue, profit, orders per segment
- Adds revenue percentage per segment
- **Purpose**: See which customer types (Champions, Loyal, At Risk…) generate most money
- **Main value**: Guides where to focus retention & marketing budget

### 2. Pareto Analysis (80/20 Rule)
- Sorts customers by descending revenue
- Calculates cumulative revenue percentage
- **Purpose**: Shows how concentrated revenue is among few customers
- **Main value**: Reveals business risk if top customers leave + supports VIP/loyalty strategy

### 3. Cohort Retention Analysis
- Assigns cohort = first purchase month
- Calculates months since first purchase (cohort index)
- **Purpose**: Tracks how retention drops over time after first buy
- **Main value**: Identifies when customers disappear → timing for re-engagement campaigns

### 4. Profitability Deep Dive (by category)
- Revenue + profit per product category
- Calculates profit margin % per category
- **Purpose**: Shows which categories are actually profitable (not just high revenue)
- **Main value**: Find loss-making products → raise prices, stop selling, renegotiate suppliers

### 5. Customer Lifetime Value (CLV) – basic version
- Total revenue + number of orders per customer
- Calculates average order value (AOV)
- **Purpose**: Estimates historical value per customer
- **Main value**: Sets maximum acquisition cost + foundation for future CLV prediction

### 6. Churn Risk Identification
- Flags customers with Recency > 180 days as High risk
- **Purpose**: Quick way to spot customers likely already gone or about to leave
- **Main value**: Creates immediate win-back list for emails, offers, discounts

### One-line summary of Step 5 overall
- Moves from basic KPIs → actionable intelligence about valuable customers, profit leaks, retention timing and churn danger.

### Revenue Contribution by Customer Segment

In [136]:
segment_analysis = df.merge(
    rfm[['customer_unique_id', 'Segment']],
    on='customer_unique_id',
    how='left'
)
segment_analysis.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,profit,year,month,day,weekday,purchase_month,cohort_month,cohort_index,freight_ratio,Segment
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,14.718,2017,10,2,Monday,2017-10,2017-09,1,0.225265,At Risk
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,14.718,2017,10,2,Monday,2017-10,2017-09,1,0.225265,At Risk
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,1,87285b34884572647811a353c7ac498a,...,14.718,2017,10,2,Monday,2017-10,2017-09,1,0.225265,At Risk
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,1,595fac2a385ac33a80bd5114aec74eb8,...,46.500,2018,7,24,Tuesday,2018-07,2018-07,0,0.160894,Loyal Customers
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,1,aa4383b373c6aca5d8797843e5594415,...,51.200,2018,8,8,Wednesday,2018-08,2018-08,0,0.107302,Regular

In [135]:
segment_summary = segment_analysis.groupby('Segment').agg({
    'revenue': 'sum',
    'profit': 'sum',
    'order_id': 'nunique'
}).reset_index()
segment_summary.head()

           Segment     revenue       profit  order_id
0          At Risk  6478068.82  2011269.028     38265
1        Champions   471092.08   140687.904      1437
2  Loyal Customers  2278464.38   735143.300     14917
3          Regular  6882866.28  2174807.248     41835

In [137]:
segment_summary['revenue_%'] = (
    segment_summary['revenue'] / segment_summary['revenue'].sum()
) * 100
segment_summary['revenue_%'].head()

0    40.210249
1     2.924132
2    14.142737
3    42.722882
Name: revenue_%, dtype: float64

### Pareto Analysis (80/20 Rule)

In [138]:
customer_revenue = df.groupby('customer_unique_id')['revenue'].sum().reset_index()
customer_revenue = customer_revenue.sort_values('revenue', ascending=False)

customer_revenue['cumulative_%'] = (
    customer_revenue['revenue'].cumsum() /
    customer_revenue['revenue'].sum()
) * 100

customer_revenue['cumulative_%'].head()

3724     0.084815
71801    0.153785
48724    0.219290
69541    0.281705
86868    0.333779
Name: cumulative_%, dtype: float64

### Cohort Retention Analysis (Advanced)

In [139]:
## Create purchase month:
df['purchase_month'] = df['order_purchase_timestamp'].dt.to_period('M')
## Customer first purchase month:
df['cohort_month'] = df.groupby('customer_unique_id')['purchase_month'].transform('min')

In [97]:
##  Cohort Index:
df['cohort_index'] = (
    (df['purchase_month'].dt.year - df['cohort_month'].dt.year) * 12 +
    (df['purchase_month'].dt.month - df['cohort_month'].dt.month)
)

In [140]:
df['cohort_index'].head()

0    1
1    1
2    1
3    0
4    0
Name: cohort_index, dtype: int64

### Profitability Deep Dive

In [99]:
category_profit = df.groupby('product_category_name').agg({
    'revenue': 'sum',
    'profit': 'sum'
}).reset_index()

category_profit['profit_margin_%'] = (
    category_profit['profit'] / category_profit['revenue']
) * 100

### Customer Lifetime Value (CLV)

In [129]:
clv = df.groupby('customer_unique_id').agg({
    'revenue': 'sum',
    'order_id': 'nunique'
}).reset_index()

clv = clv.rename(columns={'revenue': 'total_revenue', 'order_id': 'order_count'})

clv['avg_order_value'] = clv['total_revenue'] / clv['order_count']

In [131]:
clv.head()

,customer_unique_id,total_revenue,order_count,avg_order_value
0,0000366f3b9a7992bf8c76cfdf3221e2,141.90,1,141.90
1,0000b849f77a49e4a4ce2b2a4ca5be3f,27.19,1,27.19
2,0000f46a3911fa3c0805444483337064,86.22,1,86.22
3,0000f6ccb0745a6a4b88665a16c9f078,43.62,1,43.62
4,0004aac84e0df4da2b147fca70cf8255,196.89,1,196.89

### Churn Risk Identification

In [149]:
rfm['Churn_Risk'] = rfm['Recency'].apply(
    lambda x: 'High' if x > 180 else 'Low'
)
rfm['Churn_Risk'].value_counts().sum()

np.int64(93335)

## STEP 6 – DASHBOARD, VISUALIZATION & REPORTING

### Data Preparation for Dashboard
Before visualization, you must create clean summary tables.

Required Tables:
    
KPI Summary Table

Monthly Revenue Trend Table

Category Performance Table

State-wise Performance Table

RFM Segment Summary

CLV Table

###  Executive KPI Dashboard

Total Revenue

Total Profit

Profit Margin %

Total Orders

Total Customers

Average Order Value (AOV)

In [152]:
kpi_summary = pd.DataFrame({
    "Metric": ["Total Revenue","Total Profit","Profit Margin","Total Orders","Total Customers","AOV"],
    "Value": [
        df['revenue'].sum(),
        df['profit'].sum(),
        (df['profit'].sum()/df['revenue'].sum())*100,
        df['order_id'].nunique(),
        df['customer_unique_id'].nunique(),
        df['revenue'].mean()
    ]
})

In [153]:
monthly_revenue = df.groupby('purchase_month').agg({
    'revenue':'sum',
    'profit':'sum'
}).reset_index()

In [154]:
state_summary = df.groupby('customer_state').agg({
    'revenue':'sum',
    'profit':'sum',
    'order_id':'count'
}).reset_index()

### Time-Series Revenue Visualization

Chart Type:

Line Chart

What It Shows:

Monthly revenue trend

Growth rate

Seasonality

Why Used:

Identify business growth

Detect slow periods

Forecast future revenue

### Category Performance Chart

Chart Type:
    
Bar Chart

Show:
    
Revenue by category

Profit by category

Profit margin %

Why Used:

Identify top-selling categories

Detect low-margin segments

Pricing optimization decisions

You can also build:

Top 10 categories only

Profit vs Revenue scatter plot

In [110]:
category_summary = df.groupby('product_category_name').agg({
    'revenue':'sum',
    'profit':'sum',
    'order_id':'count'
}).reset_index()

category_summary['profit_margin_%'] = (
    category_summary['profit'] /
    category_summary['revenue']
) * 100

###  Geographic Analysis

Chart Type:
    
Map Visualization (State-wise)

Show:

Revenue by state

Profit by state

Why:

Regional expansion strategy

Logistics optimization

Targeted marketing

### RFM Segmentation Dashboard

Show:

Customer count by segment

Revenue contribution by segment

Profit contribution by segment

Chart types:

Pie chart (distribution)

Bar chart (revenue by segment)

Why:

Understand customer quality

Identify high-value segments

Plan retention campaigns

In [111]:
rfm['Segment'].value_counts()

Segment
Regular            41177
At Risk            37199
Loyal Customers    13976
Champions            983
Name: count, dtype: int64

In [112]:
segment_revenue = df.merge(
    rfm[['customer_unique_id','Segment']],
    on='customer_unique_id'
)

segment_summary = segment_revenue.groupby('Segment').agg({
    'revenue':'sum',
    'profit':'sum'
}).reset_index()

In [113]:
segment_summary = segment_revenue.groupby('Segment').agg({
    'revenue':'sum',
    'profit':'sum'
}).reset_index()

In [114]:
clv = df.groupby('customer_unique_id').agg({
    'revenue':'sum',
    'order_id':'nunique'
}).reset_index()

In [115]:
clv['avg_order_value'] = clv['revenue'] / clv['order_id']

In [116]:
negative_orders = df[df['profit'] < 0]

In [117]:
df['freight_ratio'] = df['freight_value'] / df['revenue']

In [118]:
state_summary['profit_margin_%'] = (
    state_summary['profit'] /
    state_summary['revenue']
) * 100

# Pareto Analysis (80/20)

Chart:

Cumulative Revenue Curve

Why:

Check revenue concentration risk

Identify dependency on top customers

If 20% customers generate 80% revenue → business concentration risk.

In [119]:
customer_rev = df.groupby('customer_unique_id')['revenue'].sum().reset_index()
customer_rev = customer_rev.sort_values('revenue', ascending=False)
customer_rev['cumulative_%'] = (
    customer_rev['revenue'].cumsum() /
    customer_rev['revenue'].sum()
) * 100

In [120]:
customer_rev[customer_rev['cumulative_%'] <= 80]

                     customer_unique_id   revenue  cumulative_%
3724   0a0a92112bd4c708ca5fde585afaa872  13664.08      0.084815
71801  c4b224d2c784bae11ae98b6ae9f2454c  11111.40      0.153785
48724  85963fd37bfd387aa6d915d8a1065486  10553.28      0.219290
69541  be74c431147c32ab2d7c7cef5e4a995f  10055.22      0.281705
86868  edf81e1f3070b9dac83ec83dacdbb9bc   8389.52      0.333779
...                                 ...       ...           ...
50580  8aca3d81c4ae8e100beceff7c7863683    114.84     79.996726
54278  950f69e2fae63ccd5306152526889e6b    114.84     79.997438
36396  638b3aff46974791ab154d575190c706    114.84     79.998151
8984   18732136dfb87593d4915dd33b402350    114.84     79.998864
17551  2fece77e050a5fe2f55351a54c822923    114.84     79.999577

[44851 rows x 3 columns]

### Cohort Retention Heatmap

Chart:

Retention heatmap (Month 0, Month 1, Month 2…)

Why:

Understand customer lifecycle

Detect churn timing

Improve retention strategy

This is advanced analytics level.

In [121]:
clv = df.groupby('customer_unique_id').agg({
    'revenue':'sum',
    'order_id':'nunique'
}).reset_index()

## Profitability Deep Dive Panel

Show:

Negative profit orders

High freight impact categories

Low margin states

Why:

Detect cost leakages

Improve margin control

Support operational optimization

### Tools You Can Use

### Option 1: Python (Matplotlib / Seaborn / Plotly)
Good for portfolio projects.

### Option 2: Power BI / Tableau
Best for industry presentation.

### Option 3: Streamlit Dashboard
If you want deployable web app.

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115011 entries, 0 to 115029
Data columns (total 44 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115011 non-null  object
 1   customer_id                    115011 non-null  object
 2   order_status                   115011 non-null  object
 3   order_purchase_timestamp       115011 non-null  datetime64[ns]
 4   order_approved_at              115011 non-null  datetime64[ns]
 5   order_delivered_carrier_date   115011 non-null  datetime64[ns]
 6   order_delivered_customer_date  115011 non-null  datetime64[ns]
 7   order_estimated_delivery_date  115011 non-null  datetime64[ns]
 8   order_item_id                  115011 non-null  int64
 9   product_id                     115011 non-null  object
 10  seller_id                      115011 non-null  object
 11  shipping_limit_date            115011 non-null  object
 12  price                          115011 non-null  float64
 13  freight_value                  115011 non-null  float64
 14  product_category_name          115011 non-null  object
 15  product_name_lenght            113384 non-null  float64
 16  product_description_lenght     113384 non-null  float64
 17  product_photos_qty             113384 non-null  float64
 18  product_weight_g               115011 non-null  float64
 19  product_length_cm              115011 non-null  float64
 20  product_height_cm              115011 non-null  float64
 21  product_width_cm               115011 non-null  float64
 22  customer_unique_id             115011 non-null  object
 23  customer_zip_code_prefix       115011 non-null  int64
 24  customer_city                  115011 non-null  object
 25  customer_state                 115011 non-null  object
 26  payment_sequential             115011 non-null  float64
 27  payment_type                   115011 non-null  object
 28  payment_installments           115011 non-null  float64
 29  payment_value                  115011 non-null  float64
 30  seller_zip_code_prefix         115011 non-null  int64
 31  seller_city                    115011 non-null  object
 32  seller_state                   115011 non-null  object
 33  revenue                        115011 non-null  float64
 34  cost                           115011 non-null  float64
 35  profit                         115011 non-null  float64
 36  year                           115011 non-null  int32
 37  month                          115011 non-null  int32
 38  day                            115011 non-null  int32
 39  weekday                        115011 non-null  object
 40  purchase_month                 115011 non-null  period[M]
 41  cohort_month                   115011 non-null  period[M]
 42  cohort_index                   115011 non-null  int64
 43  freight_ratio                  115011 non-null  float64
dtypes: datetime64[ns](5), float64(16), int32(3), int64(4), object(14), period[M](2)
memory usage: 38.2+ MB